[tool.poetry]
name = "frontend"
version = "0.1.0"
description = ""
authors = ["Gohei Kusumi"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
chainlit = "^1.1.402"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
